' Gambas module file

Public Function getParent(key As String) As String
  
  Dim iPos As Integer
  Dim sBuffer As String
  Dim sArrayEl As String
  
  If String.RInStr(key, "]") = Len(key) Then 
     Print "element of array found"
   '  iPos = String.RInStr(key, "[")
      iPos = String.RInStr(key, "[") - 1
      sArrayEl = Left$(key, iPos)
      Print "Found ArrayEl " & sArrayEl
      Return sArrayEl
  Endif
  If String.RInStr(key, "~") Then Return Left$(key, Len(key) - 1)
    iPos = String.RInStr(key, "/")
    iPos = IIf(iPos > 1, iPos - 1, iPos)


  sBuffer = Left$(key, iPos)
  If key = "/" Then sBuffer = "$"
  
  Return sBuffer
  
  
End



'****
' Case element
'  Case ws
'  Case Value
'    Case object
    
      '{' ws '}'
      '{' members '}'
'          Case members
'            member
'            member ',' members
'             case member
'                 ws string ws ':' element
'    Case array
      
        '[' ws ']'
        '[' elements ']'
'    Case string
        '"' characters '"'
''    Case number
 '     IsNumber
'    Case "true"
      
'    Case "false"
'    Case "null"
 '     * * * * * * '
 
 
'  " is a string"
' { is an object
' [ is an Array
